#!/bin/bash

export DOTFILES="$HOME/.dotfiles"

export LANG="en_US.UTF-8"
export EDITOR="nano"
{ echo "$MANPATH" | grep -q '/usr/local/man' } || export MANPATH="/usr/local/man:$MANPATH"
[ -x /usr/bin/most ] && PAGER="most"

PATH="$PATH:$DOTFILES/bin"
